### ISSUE TITLE
To-do list...

### ISSUE THREAD

**Issue by jkbptrsn** [jkbptrsn/NeedForSpeed#42]
- [ ] Compare
  - [ ] Tridiagonal matrix solver: d1dx1 with forward/backward boundary and d2dx2 with zero boundary
  - [ ] Pentadiagonal matrix solver: d1dx1 with central and forward/backward boundaries and d2dx2 with central and zero boundaries
- [ ] Remember that accuracy of solution depends on choice of boundary conditions
  - [ ] d2dx2 with zero boundary only works well, when solution actually has d2Vdx2 = 0 on boundary.
